network:
  name: MultiHeadTaskRegressor
  config_list: ['cnnAttvscnn/regressor_1a.yml', 'cnnAttvscnn/regressor_1a.yml', 'cnnAttvscnn/regressor_1a.yml']
  losses: ['L1']
  main_loss: "L1"
  margin_loss: True
  margin_loss_w: 0
  w_losses: [1, 0, 0, 0]
  mode: 'cnn'

