network:
  name: MultiHeadTaskRegressor
  config_list: ['unet/unet1.yml', 'unet/unet1.yml', 'unet/unet1.yml', 'unet/unet1.yml']
  losses: ['L1', 'L1', 'L1', 'L1']
  main_loss: "L1"
  margin_loss: True
  margin_loss_w: 1
  w_losses: [1, 1, 1, 1]
  mode: 'unet'


  

